import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCircle } from '@fortawesome/free-solid-svg-icons';

import { FaCircle } from 'react-icons/fa';

const characterEndpoint = `https://rickandmortyapi.com/api/character/`;

export async function getServerSideProps() {
  const res = await fetch(characterEndpoint);
  const data = await res.json();
  console.log(data);
  return { props: { data } };
}

export default function Home({ data }) {
  const { results = [] } = data;

  console.log(results);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wubba lubba dub duub</h1>

        <ul className={styles.grid}>
          {results.map((c) => {
            const { id, name, image } = c;

            return (
              <li key={id} className={styles.card}>
                <div className={styles.image}>
                  <img src={image} alt={`${name} Thumbnail`} />
                </div>
                <div className={styles.info}>
                  <h2 className={styles.name}>{name}</h2>
                  <div className={styles.status}>
                    <h5>
                      <span>
                        <FaCircle
                          className={
                            c.status == 'Alive' ? styles.green : styles.red
                          }
                        />
                      </span>
                      {c.status == 'Alive' ? 'Alive' : 'Dead'} - {c.species}
                    </h5>

                    <h4> </h4>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
