import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const characterEndpoint = `https://rickandmortyapi.com/api/character/`;

export async function getServerSideProps() {
  const res = await fetch(characterEndpoint);
  const data = await res.json();
  console.log(data);
  return { props: { data } };
}

export default function Home({ data }) {
  const { results = [] } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wubba lubba dub duuub!</h1>

        <ul className={styles.grid}>
          {results.map((c) => {
            const { id, name, image } = c;
            console.log(name);

            return (
              <li key={id} className={styles.card}>
                <img src={image} alt={`${name} Thumbnail`} />
                <h3>{name}</h3>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
